[Enhancement] Adds Visual Regression Testing to PR Environment Testing
platformsh-templates/drupal10 pull request #6
Opened 2023-01-26 23:11 UTC by gilzow

## Description
Updates the `TestPrEnvironment` workflow to use the [`platformsh/gha-template-pr-tests`](https://github.com/platformsh/gha-template-pr-tests) action, which now includes visual regression testing. Adds template-specific collection of paths to test. 

## Motivation and Context
To catch issues/regressions introduced during new pull requests.

## Types of changes
What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
 Go over all the following list, and put an `x` in all the boxes that apply. If you're unsure about what any of these mean, don't hesitate to ask. We're here to help!

- [X] I have read the contribution guide
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-01-26 23:20 UTC, gilzow commented
Are we missing a configuration or step in the build? When I created the PR, the PR environment didn't recognize that it was already installed and was prompting me to walk through the installer...

2023-01-26 23:33 UTC, gilzow commented
Woohoo!
https://github.com/platformsh-templates/drupal10/actions/runs/4019963029/jobs/6907551726#step:2:502

2023-01-27 19:54 UTC, chadwcarlson requested changes

2023-01-27 19:54 UTC, chadwcarlson commented on .github/workflows/sourceops.yaml
> +          curl -fsS https://raw.githubusercontent.com/gilzow/source-operations-debug/main/setup.sh | { bash /dev/fd/3 trigger-sopupdate; } 3<&0
```suggestion
          curl -fsS https://raw.githubusercontent.com/platformsh/source-operations/main/setup.sh | { bash /dev/fd/3 trigger-sopupdate; } 3<&0
```

2023-01-27 20:19 UTC, chadwcarlson approved these changes

2023-01-27 20:19 UTC, merged